import React from 'react';
import { useProjectStore } from '../../store/projectStore';
import './PrintStyles.css';
import { Printer, FileText } from 'lucide-react';

export const ReportViewer: React.FC = () => {
  const { nodes, elements, materials, sections, loadCases, results, name } = useProjectStore();

  const handlePrint = () => {
    window.print();
  };

  const hasResults = results && Object.keys(results.loadCases).length > 0;

  return (
    <div className="report-viewer-container" style={{ width: '100%', height: '100%', overflow: 'auto', backgroundColor: '#e5e7eb', padding: '24px' }}>
      {/* Non-printable header for actions */}
      <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '24px', maxWidth: '210mm', margin: '0 auto 24px auto' }}>
        <h2 style={{ color: '#111827', margin: 0, display: 'flex', alignItems: 'center', gap: '8px' }}>
          <FileText size={24} /> Structural Analysis Report
        </h2>
        <button 
          onClick={handlePrint}
          style={{ display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 16px', background: '#3b82f6', color: 'white', border: 'none', borderRadius: '6px', fontWeight: 600, cursor: 'pointer', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}
        >
          <Printer size={18} /> Print to PDF
        </button>
      </div>

      {/* A4 Paper Canvas */}
      <div className="report-viewer" style={{ 
        width: '210mm', 
        minHeight: '297mm', 
        padding: '20mm', 
        margin: '0 auto', 
        backgroundColor: 'white', 
        boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
        borderRadius: '2px',
        color: '#000',
        fontFamily: '"Times New Roman", Times, serif',
        lineHeight: 1.5
      }}>
        
        {/* Cover Page */}
        <div className="page-break-after" style={{ height: '240mm', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textAlign: 'center' }}>
          <h1 style={{ fontSize: '36pt', marginBottom: '16px', fontWeight: 'bold' }}>Structural Calculation Report</h1>
          <h2 style={{ fontSize: '24pt', color: '#4b5563', marginBottom: '48px', fontWeight: 'normal' }}>Project: {name || 'Untitled Project'}</h2>
          
          <div style={{ marginTop: 'auto', borderTop: '2px solid #000', paddingTop: '16px', width: '100%' }}>
            <p style={{ fontSize: '14pt', margin: '4px 0' }}>Generated by <strong>AMEVA Civil</strong></p>
            <p style={{ fontSize: '12pt', color: '#6b7280' }}>Date: {new Date().toLocaleDateString()}</p>
          </div>
        </div>

        {/* Captured 3D View */}
        {useProjectStore.getState().captureImage && (
          <div className="avoid-page-break" style={{ marginBottom: '40px' }}>
            <h2 style={{ borderBottom: '2px solid #000', paddingBottom: '8px', marginTop: '32px' }}>1. 3D Model Overview</h2>
            <div style={{ textAlign: 'center', marginTop: '16px' }}>
              <img src={useProjectStore.getState().captureImage} alt="3D Model Capture" style={{ maxWidth: '100%', border: '1px solid #d1d5db', borderRadius: '4px', padding: '4px' }} />
              <p style={{ fontSize: '10pt', color: '#6b7280', marginTop: '8px' }}>Figure 1: 3D Model View captured from workspace.</p>
            </div>
          </div>
        )}

        {/* Section 1: Model Information */}
        <div className="avoid-page-break">
          <h2 style={{ borderBottom: '2px solid #000', paddingBottom: '8px', marginTop: '32px' }}>2. Model Information</h2>
          
          <h3 style={{ marginTop: '24px' }}>2.1 Node Data</h3>
          <table>
            <thead>
              <tr>
                <th>Node ID</th>
                <th>X (m)</th>
                <th>Y (m)</th>
                <th>Z (m)</th>
              </tr>
            </thead>
            <tbody>
              {Object.values(nodes).map(node => (
                <tr key={node.id}>
                  <td>{node.id}</td>
                  <td>{node.x.toFixed(3)}</td>
                  <td>{node.y.toFixed(3)}</td>
                  <td>{node.z.toFixed(3)}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <h3 style={{ marginTop: '24px' }}>2.2 Element Data</h3>
          <table>
            <thead>
              <tr>
                <th>Element ID</th>
                <th>Start Node</th>
                <th>End Node</th>
                <th>Material</th>
                <th>Section</th>
              </tr>
            </thead>
            <tbody>
              {Object.values(elements).map(el => (
                <tr key={el.id}>
                  <td>{el.id}</td>
                  <td>{el.startNodeId}</td>
                  <td>{el.endNodeId}</td>
                  <td>{materials[el.materialId]?.name || el.materialId}</td>
                  <td>{sections[el.sectionId]?.name || el.sectionId}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Section 3: Eigenvalue Results (Phase 13) */}
        {results?.eigenvalues && (
          <div className="avoid-page-break" style={{ marginTop: '40px' }}>
            <h2 style={{ borderBottom: '2px solid #000', paddingBottom: '8px' }}>3. Eigenvalue Analysis Results</h2>
            <p style={{ marginTop: '16px', fontSize: '11pt' }}>The following table summarizes the natural frequencies and periods for the first {results.eigenvalues.frequencies.length} modes, calculated using a simplified lumped mass matrix approach.</p>
            <table style={{ marginTop: '16px' }}>
              <thead>
                <tr>
                  <th>Mode No.</th>
                  <th>Frequency (Hz)</th>
                  <th>Period (s)</th>
                </tr>
              </thead>
              <tbody>
                {results.eigenvalues.frequencies.map((freq, idx) => (
                  <tr key={`mode-${idx}`}>
                    <td>{idx + 1}</td>
                    <td>{freq.toFixed(4)}</td>
                    <td>{(1 / freq).toFixed(4)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* Section 4: Analysis Results */}
        <div className="page-break">
          <h2 style={{ borderBottom: '2px solid #000', paddingBottom: '8px' }}>4. Static Analysis Results</h2>
          
          {!hasResults ? (
            <p style={{ color: '#ef4444', fontStyle: 'italic', marginTop: '16px' }}>No analysis results available. Please run the solver first.</p>
          ) : (
            Object.entries(results.loadCases).map(([lcId, res]) => (
              <div key={lcId} className="avoid-page-break" style={{ marginBottom: '40px' }}>
                <h3 style={{ marginTop: '24px', backgroundColor: '#f3f4f6', padding: '8px', borderLeft: '4px solid #3b82f6' }}>Load Case: {loadCases[lcId]?.name || lcId}</h3>
                
                <h4 style={{ marginTop: '16px' }}>Nodal Displacements (m, rad)</h4>
                <table>
                  <thead>
                    <tr>
                      <th>Node ID</th>
                      <th>DX</th>
                      <th>DY</th>
                      <th>DZ</th>
                      <th>RX</th>
                      <th>RY</th>
                      <th>RZ</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(res.displacements).slice(0, 30).map(([nodeId, d]) => (
                      <tr key={nodeId}>
                        <td>{nodeId}</td>
                        <td>{d.dx.toExponential(3)}</td>
                        <td>{d.dy.toExponential(3)}</td>
                        <td>{d.dz.toExponential(3)}</td>
                        <td>{d.rx.toExponential(3)}</td>
                        <td>{d.ry.toExponential(3)}</td>
                        <td>{d.rz.toExponential(3)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                {Object.keys(res.displacements).length > 30 && <p style={{ fontSize: '9pt', color: '#6b7280' }}>* Showing first 30 nodes</p>}

                <h4 style={{ marginTop: '24px' }}>Support Reactions (kN, kNm)</h4>
                <table>
                  <thead>
                    <tr>
                      <th>Node ID</th>
                      <th>FX</th>
                      <th>FY</th>
                      <th>FZ</th>
                      <th>MX</th>
                      <th>MY</th>
                      <th>MZ</th>
                    </tr>
                  </thead>
                  <tbody>
                    {Object.entries(res.reactions).map(([nodeId, r]) => {
                      if (Math.abs(r.fx) < 1e-6 && Math.abs(r.fy) < 1e-6 && Math.abs(r.fz) < 1e-6 && Math.abs(r.mx) < 1e-6 && Math.abs(r.my) < 1e-6 && Math.abs(r.mz) < 1e-6) return null;
                      return (
                        <tr key={nodeId}>
                          <td>{nodeId}</td>
                          <td>{r.fx.toFixed(2)}</td>
                          <td>{r.fy.toFixed(2)}</td>
                          <td>{r.fz.toFixed(2)}</td>
                          <td>{r.mx.toFixed(2)}</td>
                          <td>{r.my.toFixed(2)}</td>
                          <td>{r.mz.toFixed(2)}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>

                <div className="page-break">
                  <h4 style={{ marginTop: '24px' }}>Element Forces (kN, kNm) & Principal Stresses (MPa)</h4>
                  <table>
                    <thead>
                      <tr>
                        <th>Elem ID</th>
                        <th>Node</th>
                        <th>Axial (P)</th>
                        <th>Shear-y (Vy)</th>
                        <th>Shear-z (Vz)</th>
                        <th>Moment-y (My)</th>
                        <th>Moment-z (Mz)</th>
                        <th>Von Mises Stress</th>
                      </tr>
                    </thead>
                    <tbody>
                      {Object.entries(res.elementForces).map(([elId, forces]) => (
                        <React.Fragment key={elId}>
                          <tr>
                            <td rowSpan={2} style={{ verticalAlign: 'middle' }}><strong>{elId}</strong></td>
                            <td>Start</td>
                            <td>{forces.nodes.start.fx.toFixed(2)}</td>
                            <td>{forces.nodes.start.fy.toFixed(2)}</td>
                            <td>{forces.nodes.start.fz.toFixed(2)}</td>
                            <td>{forces.nodes.start.my.toFixed(2)}</td>
                            <td>{forces.nodes.start.mz.toFixed(2)}</td>
                            <td rowSpan={2} style={{ verticalAlign: 'middle', fontWeight: 'bold' }}>
                              {forces.principalStresses?.maxVonMises ? forces.principalStresses.maxVonMises.toFixed(2) : '-'}
                            </td>
                          </tr>
                          <tr>
                            <td>End</td>
                            <td>{forces.nodes.end.fx.toFixed(2)}</td>
                            <td>{forces.nodes.end.fy.toFixed(2)}</td>
                            <td>{forces.nodes.end.fz.toFixed(2)}</td>
                            <td>{forces.nodes.end.my.toFixed(2)}</td>
                            <td>{forces.nodes.end.mz.toFixed(2)}</td>
                          </tr>
                        </React.Fragment>
                      ))}
                    </tbody>
                  </table>
                </div>

              </div>
            ))
          )}
        </div>

      </div>
    </div>
  );
};
